### ISSUE TITLE
uci: Entry not found

### ISSUE THREAD

**Issue by beinginorbit** [4IceG/luci-app-socat#1]
Upon installation just getting a minor error. Thanks for this package by the way.

```
uci: Entry not found
```

It installs but I think it's not putting the entry for the menu bar into luci.

**Comment by 4IceG** [comment]
Installation errors can be but the application works and is in the menu,
just log out and log in again or restart the router.

niedz., 10 paź 2021, 05:18 użytkownik Chris LeBlanc <
***@***.***> napisał:

**Comment by 4IceG** [comment]
I made the application fast but it works, I tested it before publication.

niedz., 10 paź 2021, 06:40 użytkownik Rafał ***@***.***> napisał:

**Comment by beinginorbit** [comment]
You’re right. I usually see the menu on refresh but had to log back in.
